// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/debugchangestream/service (interfaces: State)
//
// Generated by this command:
//
//	mockgen -typed -package service -destination state_mock_test.go github.com/juju/juju/domain/debugchangestream/service State
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// AllNodesReachedTxn mocks base method.
func (m *MockState) AllNodesReachedTxn(
	arg0 context.Context, arg1 int64,
) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllNodesReachedTxn", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllNodesReachedTxn indicates an expected call of AllNodesReachedTxn.
func (mr *MockStateMockRecorder) AllNodesReachedTxn(
	arg0, arg1 any,
) *MockStateAllNodesReachedTxnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"AllNodesReachedTxn",
		reflect.TypeOf((*MockState)(nil).AllNodesReachedTxn),
		arg0, arg1,
	)
	return &MockStateAllNodesReachedTxnCall{Call: call}
}

// MockStateAllNodesReachedTxnCall wrap *gomock.Call
type MockStateAllNodesReachedTxnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateAllNodesReachedTxnCall) Return(
	arg0 bool, arg1 error,
) *MockStateAllNodesReachedTxnCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateAllNodesReachedTxnCall) Do(
	f func(context.Context, int64) (bool, error),
) *MockStateAllNodesReachedTxnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateAllNodesReachedTxnCall) DoAndReturn(
	f func(context.Context, int64) (bool, error),
) *MockStateAllNodesReachedTxnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CurrentTxnID mocks base method.
func (m *MockState) CurrentTxnID(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentTxnID", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentTxnID indicates an expected call of CurrentTxnID.
func (mr *MockStateMockRecorder) CurrentTxnID(
	arg0 any,
) *MockStateCurrentTxnIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"CurrentTxnID",
		reflect.TypeOf((*MockState)(nil).CurrentTxnID),
		arg0,
	)
	return &MockStateCurrentTxnIDCall{Call: call}
}

// MockStateCurrentTxnIDCall wrap *gomock.Call
type MockStateCurrentTxnIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateCurrentTxnIDCall) Return(
	arg0 int64, arg1 error,
) *MockStateCurrentTxnIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateCurrentTxnIDCall) Do(
	f func(context.Context) (int64, error),
) *MockStateCurrentTxnIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateCurrentTxnIDCall) DoAndReturn(
	f func(context.Context) (int64, error),
) *MockStateCurrentTxnIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DebugState mocks base method.
func (m *MockState) DebugState(
	arg0 context.Context,
) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebugState", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DebugState indicates an expected call of DebugState.
func (mr *MockStateMockRecorder) DebugState(
	arg0 any,
) *MockStateDebugStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"DebugState",
		reflect.TypeOf((*MockState)(nil).DebugState),
		arg0,
	)
	return &MockStateDebugStateCall{Call: call}
}

// MockStateDebugStateCall wrap *gomock.Call
type MockStateDebugStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateDebugStateCall) Return(
	arg0 string, arg1 int64, arg2 error,
) *MockStateDebugStateCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateDebugStateCall) Do(
	f func(context.Context) (string, int64, error),
) *MockStateDebugStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateDebugStateCall) DoAndReturn(
	f func(context.Context) (string, int64, error),
) *MockStateDebugStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EventCountInRange mocks base method.
func (m *MockState) EventCountInRange(
	arg0 context.Context, arg1, arg2 int64,
) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventCountInRange", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventCountInRange indicates an expected call of EventCountInRange.
func (mr *MockStateMockRecorder) EventCountInRange(
	arg0, arg1, arg2 any,
) *MockStateEventCountInRangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"EventCountInRange",
		reflect.TypeOf((*MockState)(nil).EventCountInRange),
		arg0, arg1, arg2,
	)
	return &MockStateEventCountInRangeCall{Call: call}
}

// MockStateEventCountInRangeCall wrap *gomock.Call
type MockStateEventCountInRangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateEventCountInRangeCall) Return(
	arg0 int, arg1 error,
) *MockStateEventCountInRangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateEventCountInRangeCall) Do(
	f func(context.Context, int64, int64) (int, error),
) *MockStateEventCountInRangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateEventCountInRangeCall) DoAndReturn(
	f func(context.Context, int64, int64) (int, error),
) *MockStateEventCountInRangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetPaused mocks base method.
func (m *MockState) SetPaused(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPaused", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPaused indicates an expected call of SetPaused.
func (mr *MockStateMockRecorder) SetPaused(
	arg0 any,
) *MockStateSetPausedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SetPaused",
		reflect.TypeOf((*MockState)(nil).SetPaused),
		arg0,
	)
	return &MockStateSetPausedCall{Call: call}
}

// MockStateSetPausedCall wrap *gomock.Call
type MockStateSetPausedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateSetPausedCall) Return(
	arg0 error,
) *MockStateSetPausedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateSetPausedCall) Do(
	f func(context.Context) error,
) *MockStateSetPausedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateSetPausedCall) DoAndReturn(
	f func(context.Context) error,
) *MockStateSetPausedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRunning mocks base method.
func (m *MockState) SetRunning(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRunning", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRunning indicates an expected call of SetRunning.
func (mr *MockStateMockRecorder) SetRunning(
	arg0 any,
) *MockStateSetRunningCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SetRunning",
		reflect.TypeOf((*MockState)(nil).SetRunning),
		arg0,
	)
	return &MockStateSetRunningCall{Call: call}
}

// MockStateSetRunningCall wrap *gomock.Call
type MockStateSetRunningCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateSetRunningCall) Return(
	arg0 error,
) *MockStateSetRunningCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateSetRunningCall) Do(
	f func(context.Context) error,
) *MockStateSetRunningCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateSetRunningCall) DoAndReturn(
	f func(context.Context) error,
) *MockStateSetRunningCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStep mocks base method.
func (m *MockState) SetStep(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStep", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStep indicates an expected call of SetStep.
func (mr *MockStateMockRecorder) SetStep(
	arg0, arg1 any,
) *MockStateSetStepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"SetStep",
		reflect.TypeOf((*MockState)(nil).SetStep),
		arg0, arg1,
	)
	return &MockStateSetStepCall{Call: call}
}

// MockStateSetStepCall wrap *gomock.Call
type MockStateSetStepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateSetStepCall) Return(arg0 error) *MockStateSetStepCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateSetStepCall) Do(
	f func(context.Context, int64) error,
) *MockStateSetStepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateSetStepCall) DoAndReturn(
	f func(context.Context, int64) error,
) *MockStateSetStepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
